name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install dependencies
        run: make install-apt-deps

      - name: Compile using xelatex
        run: make cv

      - name: Auto commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated CV [GitHub Action]"
