name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile pdfs
    runs-on: ubuntu-latest
    container: mrlento234/xelatex

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile cv
        run: xelatex cv.tex

      - name: Upload pdfs
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf
