name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile pdfs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile cv
        run: xelatex cv.tex

      - name: Upload pdfs
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf

  commit:
    name: Commit changes
    runs-on: ubuntu-latest

    steps:
      - name: Commit pdf to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes