name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    container: mrlento234/xelatex

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile using xelatex
        run: make cv

      - name: Release CV
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
