name: Check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check CV
    runs-on: ubuntu-latest
    container: mrlento234/xelatex

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Compile using xelatex
        run: make cv
